const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Mouse,
		C3.Plugins.UserMedia,
		C3.Plugins.Button,
		C3.Plugins.HTMLElement,
		C3.Behaviors.Platform,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.EventGameplay_Event4_Act2,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.JavaScriptInEvents.EventGameplay_Event35_Act1,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.max,
		C3.JavaScriptInEvents.EventGameplay_Event59_Act1,
		C3.Plugins.Sprite.Exps.Y,
		C3.JavaScriptInEvents.EventGameplay_Event67_Act1,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.JavaScriptInEvents.EventMenu_Event3_Act4,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.JavaScriptInEvents.EventScore_Event2_Act1,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.tokencount,
		C3.JavaScriptInEvents.Event_leaderboard_Event3_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Json.Cnds.ForEach,
		C3.JavaScriptInEvents.Event_leaderboard_Event17_Act1,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.JavaScriptInEvents.EventInventory_Event1_Act1,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{Sine: 0},
	{BGEffect: 0},
	{value: 0},
	{item_hamie: 0},
	{Pathfinding: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles23: 0},
	{Particles3: 0},
	{score: 0},
	{counter: 0},
	{TextScore: 0},
	{Levelscore: 0},
	{countText: 0},
	{item_bitcoin: 0},
	{Anchor: 0},
	{background_bottom1: 0},
	{background_bottom2: 0},
	{background_left: 0},
	{background_right: 0},
	{background_top1: 0},
	{background_top2: 0},
	{bottom_1: 0},
	{Tween: 0},
	{Flash: 0},
	{bottom_2: 0},
	{bottom_3: 0},
	{bottom_4: 0},
	{bottom_5: 0},
	{effects_bottom_1: 0},
	{effects_bottom_2: 0},
	{effects_bottom_3: 0},
	{effects_bottom_4: 0},
	{effects_bottom_5: 0},
	{effects_top1: 0},
	{effects_top2: 0},
	{effects_top3: 0},
	{effects_top4: 0},
	{effects_top5: 0},
	{top_1: 0},
	{top_2: 0},
	{top_3: 0},
	{top_4: 0},
	{top_5: 0},
	{Cscore_count: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{background_left2: 0},
	{background_right2: 0},
	{Player6: 0},
	{Player4: 0},
	{Player1: 0},
	{Player5: 0},
	{top_6: 0},
	{top_7: 0},
	{top_8: 0},
	{top_9: 0},
	{bottom_6: 0},
	{bottom_7: 0},
	{bottom_8: 0},
	{Sprite2: 0},
	{Player2: 0},
	{Player3: 0},
	{bound_b1: 0},
	{bound_b2: 0},
	{bound_t1: 0},
	{bound_t2: 0},
	{Player0: 0},
	{background_right3: 0},
	{background_right4: 0},
	{Menu: 0},
	{Link_ID: 0},
	{Orig_Width: 0},
	{Orig_Height: 0},
	{Menu_Panel: 0},
	{Cup: 0},
	{Sine2: 0},
	{menutitle: 0},
	{background_tuturial: 0},
	{howtoplay_hamie: 0},
	{howtoplay_modal: 0},
	{howtoplay_text: 0},
	{firststart: 0},
	{Fader: 0},
	{howtoplay_back: 0},
	{tap_area: 0},
	{Sprite: 0},
	{base_shapes: 0},
	{bottom_shape: 0},
	{base_back: 0},
	{btn_inventory: 0},
	{Restart: 0},
	{hamie_log: 0},
	{Home: 0},
	{TextBest: 0},
	{btn_start: 0},
	{GameOver: 0},
	{text_finalscore: 0},
	{text_score: 0},
	{audio_active: 0},
	{audio_mute: 0},
	{text_gamescore: 0},
	{card_11_: 0},
	{Name: 0},
	{ScoreForAPerson: 0},
	{UsersInfo: 0},
	{UsersRanking: 0},
	{medal_gold: 0},
	{medal_silver: 0},
	{medal_bronze: 0},
	{Home_button: 0},
	{UsersName: 0},
	{UsersScore: 0},
	{YourRanking: 0},
	{TopBestScoreName: 0},
	{TopBestScore: 0},
	{Star: 0},
	{DragDrop: 0},
	{scoreboard: 0},
	{Rank_text: 0},
	{Rank_Header: 0},
	{btn_playnow: 0},
	{leaderboard_b1: 0},
	{leaderboard_b2: 0},
	{TextScore2: 0},
	{numGo: 0},
	{num1: 0},
	{num2: 0},
	{num3: 0},
	{UsersScore2: 0},
	{UsersScore3: 0},
	{scrollBar: 0},
	{card_top: 0},
	{Rotate: 0},
	{Sprite4: 0},
	{btn_weekly_a: 0},
	{btn_3: 0},
	{btn_2: 0},
	{btn_1: 0},
	{How_button: 0},
	{btn_weekly_b: 0},
	{btn_alltime_b: 0},
	{btn_alltime_a: 0},
	{coins_b: 0},
	{btn_totalpoints_a: 0},
	{inventoryboard: 0},
	{index: 0},
	{description: 0},
	{unlockType: 0},
	{unlockValue: 0},
	{isLocked: 0},
	{inventory_item: 0},
	{btn_background_a: 0},
	{btn_background_b: 0},
	{btn_skins_a: 0},
	{btn_skins_b: 0},
	{btn_sfx_a: 0},
	{btn_sfx_b: 0},
	{inventory_b2: 0},
	{item_selected: 0},
	{item_locked: 0},
	{inventory_lock: 0},
	{card_1_10: 0},
	{btn_highestscore_a: 0},
	{title_leaderboard: 0},
	{btn_highestscore_b: 0},
	{btn_totalpoints_b: 0},
	{btn_playagain: 0},
	{itemName: 0},
	{btn_question: 0},
	{inventory_selected: 0},
	{text_statstitle: 0},
	{score_board: 0},
	{Text: 0},
	{box_message: 0},
	{text_message: 0},
	{help_back: 0},
	{help_box: 0},
	{btn_close: 0},
	{help_body: 0},
	{scrollBoard: 0},
	{help_title: 0},
	{box_stats: 0},
	{score_weektotal: 0},
	{score_weekhigh: 0},
	{score_allhigh: 0},
	{rank_alltotal: 0},
	{rank_weektotal: 0},
	{rank_weekhigh: 0},
	{rank_allhigh: 0},
	{score_alltotal: 0},
	{stats_close: 0},
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{AJAX: 0},
	{Array: 0},
	{JSON: 0},
	{Mouse: 0},
	{TextTutorial: 0},
	{UserMedia: 0},
	{Button: 0},
	{SpriteFont: 0},
	{HTMLElement: 0},
	{secondScore: 0},
	{Platform: 0},
	{Characters: 0},
	{Backgrounds: 0},
	{Obstacles: 0},
	{Items: 0},
	{ObsEffects: 0},
	{Bounds: 0},
	{StatsTexts: 0},
	{var_state: 0},
	{music_controller1: 0},
	{game_start: 0},
	{var_score: 0},
	{var_coins: 0},
	{var_best: 0},
	{isDistroied: 0},
	{isCompleted: 0},
	{Selectedcolor: 0},
	{passCount: 0},
	{AudioFactor: 0},
	{LevelCount: 0},
	{coinLocationX: 0},
	{coinLocationY: 0},
	{gamespeedcontroller: 0},
	{start_countdown: 0},
	{best_score: 0},
	{bestWeeklyTotal: 0},
	{game_level: 0},
	{is_music_playing: 0},
	{skinId: 0},
	{backgroundId: 0},
	{sfxId: 0},
	{gIsSessionActive: 0},
	{base_url: 0},
	{telegramId: 0},
	{userName: 0},
	{fistName: 0},
	{lastName: 0},
	{BoardState: 0},
	{isNewUser: 0},
	{phoneNumber: 0},
	{tuturialNumber: 0},
	{soundMenuControlier1: 0},
	{is_muted: 0},
	{layout: 0},
	{alert_message: 0},
	{is_unlocking: 0},
	{sc_name: 0},
	{sc_ranking: 0},
	{sc_value: 0},
	{sc_value2: 0},
	{sc_value3: 0},
	{length: 0},
	{yourRank: 0},
	{yourScore: 0},
	{topBestName: 0},
	{topBestScore: 0},
	{topBest: 0},
	{a1: 0},
	{scrollBar_percent: 0},
	{loading: 0},
	{topNumber: 0},
	{tab_period: 0},
	{tab_mode: 0},
	{is_help_showing: 0},
	{base_offset: 0},
	{Iterator: 0},
	{inventory_tab: 0},
	{item_per_row: 0},
	{itemId: 0},
	{row_index: 0}
];

self.InstanceType = {
	BGEffect: class extends self.ISpriteInstance {},
	item_hamie: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles23: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	score: class extends self.ISpriteInstance {},
	counter: class extends self.ISpriteInstance {},
	TextScore: class extends self.ISpriteFontInstance {},
	Levelscore: class extends self.ISpriteFontInstance {},
	countText: class extends self.ITextInstance {},
	item_bitcoin: class extends self.ISpriteInstance {},
	background_bottom1: class extends self.ISpriteInstance {},
	background_bottom2: class extends self.ISpriteInstance {},
	background_left: class extends self.ISpriteInstance {},
	background_right: class extends self.ISpriteInstance {},
	background_top1: class extends self.ISpriteInstance {},
	background_top2: class extends self.ISpriteInstance {},
	bottom_1: class extends self.ISpriteInstance {},
	bottom_2: class extends self.ISpriteInstance {},
	bottom_3: class extends self.ISpriteInstance {},
	bottom_4: class extends self.ISpriteInstance {},
	bottom_5: class extends self.ISpriteInstance {},
	effects_bottom_1: class extends self.ISpriteInstance {},
	effects_bottom_2: class extends self.ISpriteInstance {},
	effects_bottom_3: class extends self.ISpriteInstance {},
	effects_bottom_4: class extends self.ISpriteInstance {},
	effects_bottom_5: class extends self.ISpriteInstance {},
	effects_top1: class extends self.ISpriteInstance {},
	effects_top2: class extends self.ISpriteInstance {},
	effects_top3: class extends self.ISpriteInstance {},
	effects_top4: class extends self.ISpriteInstance {},
	effects_top5: class extends self.ISpriteInstance {},
	top_1: class extends self.ISpriteInstance {},
	top_2: class extends self.ISpriteInstance {},
	top_3: class extends self.ISpriteInstance {},
	top_4: class extends self.ISpriteInstance {},
	top_5: class extends self.ISpriteInstance {},
	Cscore_count: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	background_left2: class extends self.ISpriteInstance {},
	background_right2: class extends self.ISpriteInstance {},
	Player6: class extends self.ISpriteInstance {},
	Player4: class extends self.ISpriteInstance {},
	Player1: class extends self.ISpriteInstance {},
	Player5: class extends self.ISpriteInstance {},
	top_6: class extends self.ISpriteInstance {},
	top_7: class extends self.ISpriteInstance {},
	top_8: class extends self.ISpriteInstance {},
	top_9: class extends self.ISpriteInstance {},
	bottom_6: class extends self.ISpriteInstance {},
	bottom_7: class extends self.ISpriteInstance {},
	bottom_8: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Player3: class extends self.ISpriteInstance {},
	bound_b1: class extends self.ISpriteInstance {},
	bound_b2: class extends self.ISpriteInstance {},
	bound_t1: class extends self.ISpriteInstance {},
	bound_t2: class extends self.ISpriteInstance {},
	Player0: class extends self.ISpriteInstance {},
	background_right3: class extends self.ISpriteInstance {},
	background_right4: class extends self.ISpriteInstance {},
	Menu_Panel: class extends self.ISpriteInstance {},
	Cup: class extends self.ISpriteInstance {},
	menutitle: class extends self.ISpriteInstance {},
	background_tuturial: class extends self.ISpriteInstance {},
	howtoplay_hamie: class extends self.ISpriteInstance {},
	howtoplay_modal: class extends self.ISpriteInstance {},
	howtoplay_text: class extends self.ISpriteInstance {},
	firststart: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	howtoplay_back: class extends self.ISpriteInstance {},
	tap_area: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	base_shapes: class extends self.ISpriteInstance {},
	bottom_shape: class extends self.ISpriteInstance {},
	base_back: class extends self.ISpriteInstance {},
	btn_inventory: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	hamie_log: class extends self.ISpriteInstance {},
	Home: class extends self.ISpriteInstance {},
	TextBest: class extends self.ITextInstance {},
	btn_start: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	text_finalscore: class extends self.ITextInstance {},
	text_score: class extends self.ISpriteInstance {},
	audio_active: class extends self.ISpriteInstance {},
	audio_mute: class extends self.ISpriteInstance {},
	text_gamescore: class extends self.ITextInstance {},
	card_11_: class extends self.ISpriteInstance {},
	Name: class extends self.ITextInstance {},
	ScoreForAPerson: class extends self.ITextInstance {},
	UsersInfo: class extends self.IArrayInstance {},
	UsersRanking: class extends self.ITextInstance {},
	medal_gold: class extends self.ISpriteInstance {},
	medal_silver: class extends self.ISpriteInstance {},
	medal_bronze: class extends self.ISpriteInstance {},
	Home_button: class extends self.ISpriteInstance {},
	UsersName: class extends self.ITextInstance {},
	UsersScore: class extends self.ITextInstance {},
	YourRanking: class extends self.ITextInstance {},
	TopBestScoreName: class extends self.ITextInstance {},
	TopBestScore: class extends self.ITextInstance {},
	Star: class extends self.ISpriteInstance {},
	scoreboard: class extends self.ISpriteInstance {},
	Rank_text: class extends self.ITextInstance {},
	Rank_Header: class extends self.ISpriteInstance {},
	btn_playnow: class extends self.ISpriteInstance {},
	leaderboard_b1: class extends self.ISpriteInstance {},
	leaderboard_b2: class extends self.ISpriteInstance {},
	TextScore2: class extends self.ISpriteFontInstance {},
	numGo: class extends self.ISpriteFontInstance {},
	num1: class extends self.ISpriteFontInstance {},
	num2: class extends self.ISpriteFontInstance {},
	num3: class extends self.ISpriteFontInstance {},
	UsersScore2: class extends self.ITextInstance {},
	UsersScore3: class extends self.ITextInstance {},
	scrollBar: class extends self.ISpriteInstance {},
	card_top: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	btn_weekly_a: class extends self.ISpriteInstance {},
	btn_3: class extends self.ISpriteInstance {},
	btn_2: class extends self.ISpriteInstance {},
	btn_1: class extends self.ISpriteInstance {},
	How_button: class extends self.ISpriteInstance {},
	btn_weekly_b: class extends self.ISpriteInstance {},
	btn_alltime_b: class extends self.ISpriteInstance {},
	btn_alltime_a: class extends self.ISpriteInstance {},
	coins_b: class extends self.ISpriteInstance {},
	btn_totalpoints_a: class extends self.ISpriteInstance {},
	inventoryboard: class extends self.ISpriteInstance {},
	inventory_item: class extends self.ISpriteInstance {},
	btn_background_a: class extends self.ISpriteInstance {},
	btn_background_b: class extends self.ISpriteInstance {},
	btn_skins_a: class extends self.ISpriteInstance {},
	btn_skins_b: class extends self.ISpriteInstance {},
	btn_sfx_a: class extends self.ISpriteInstance {},
	btn_sfx_b: class extends self.ISpriteInstance {},
	inventory_b2: class extends self.ISpriteInstance {},
	item_selected: class extends self.ISpriteInstance {},
	item_locked: class extends self.ISpriteInstance {},
	inventory_lock: class extends self.ISpriteInstance {},
	card_1_10: class extends self.ISpriteInstance {},
	btn_highestscore_a: class extends self.ISpriteInstance {},
	title_leaderboard: class extends self.ISpriteInstance {},
	btn_highestscore_b: class extends self.ISpriteInstance {},
	btn_totalpoints_b: class extends self.ISpriteInstance {},
	btn_playagain: class extends self.ISpriteInstance {},
	btn_question: class extends self.ISpriteInstance {},
	inventory_selected: class extends self.ISpriteInstance {},
	text_statstitle: class extends self.ITextInstance {},
	score_board: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	box_message: class extends self.ISpriteInstance {},
	text_message: class extends self.ITextInstance {},
	help_back: class extends self.ISpriteInstance {},
	help_box: class extends self.ISpriteInstance {},
	btn_close: class extends self.ISpriteInstance {},
	help_body: class extends self.ITextInstance {},
	scrollBoard: class extends self.ISpriteInstance {},
	help_title: class extends self.ITextInstance {},
	box_stats: class extends self.ISpriteInstance {},
	score_weektotal: class extends self.ITextInstance {},
	score_weekhigh: class extends self.ITextInstance {},
	score_allhigh: class extends self.ITextInstance {},
	rank_alltotal: class extends self.ITextInstance {},
	rank_weektotal: class extends self.ITextInstance {},
	rank_weekhigh: class extends self.ITextInstance {},
	rank_allhigh: class extends self.ITextInstance {},
	score_alltotal: class extends self.ITextInstance {},
	stats_close: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	Mouse: class extends self.IInstance {},
	TextTutorial: class extends self.ITextInstance {},
	UserMedia: class extends self.IWorldInstance {},
	Button: class extends self.IButtonInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	secondScore: class extends self.ITextInstance {},
	Characters: class extends self.ISpriteInstance {},
	Backgrounds: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	Items: class extends self.ISpriteInstance {},
	ObsEffects: class extends self.ISpriteInstance {},
	Bounds: class extends self.ISpriteInstance {},
	StatsTexts: class extends self.ITextInstance {}
}